#!/bin/bash

# Config
EXEC="../bin/pfsp"
INSTANCE_DIR="../instances/Benchmarks"
REPEAT=10
NEIGHBORHOODS=(--tei --tie)

MAX_JOBS=10

# Loop over all instances
for instance_file in "$INSTANCE_DIR"/*; do
    instance_name=$(basename "$instance_file")  # e.g., ta051

    echo "Running on instance: $instance_name"

    # Loop over all VND strategies
    for neighborhood in "${NEIGHBORHOODS[@]}"; do
        echo -n "  [$neighborhood] "

        # Run REPEAT times in parallel
        for ((i = 1; i <= REPEAT; i++)); do
            $EXEC "--vnd" --"$instance_name" $neighborhood > /dev/null &

            # Check the number of running jobs
            while (( $(jobs -r | wc -l) >= MAX_JOBS )); do
                sleep 0.2  # Wait for a bit before checking again
            done

            echo -n "."
        done

        wait
        echo "done"
    done
done
